//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AoTracker.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AoTracker.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications on new changes in feed being available..
        /// </summary>
        public static string Android_NotificationChannel_Description {
            get {
                return ResourceManager.GetString("Android_NotificationChannel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed Updates.
        /// </summary>
        public static string Android_NotificationChannel_Name {
            get {
                return ResourceManager.GetString("Android_NotificationChannel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase price by offset.
        /// </summary>
        public static string ConfigureCrawler_Cost_OffsetIncrease {
            get {
                return ResourceManager.GetString("ConfigureCrawler_Cost_OffsetIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increease price by fixed value applied before % increase.
        /// </summary>
        public static string ConfigureCrawler_Cost_OffsetIncrease_HelpText {
            get {
                return ResourceManager.GetString("ConfigureCrawler_Cost_OffsetIncrease_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase price by percentage.
        /// </summary>
        public static string ConfigureCrawler_Cost_PercentageIncrease {
            get {
                return ResourceManager.GetString("ConfigureCrawler_Cost_PercentageIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases the base prices by given %.
        /// </summary>
        public static string ConfigureCrawler_Cost_PercentageIncrease_HelpText {
            get {
                return ResourceManager.GetString("ConfigureCrawler_Cost_PercentageIncrease_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query needs to be shorter than 30 characters..
        /// </summary>
        public static string ConfigureCrawler_Error_SearchQueryInput_Long {
            get {
                return ResourceManager.GetString("ConfigureCrawler_Error_SearchQueryInput_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query needs to be at least 2 characters long..
        /// </summary>
        public static string ConfigureCrawler_Error_SearchQueryInput_Short {
            get {
                return ResourceManager.GetString("ConfigureCrawler_Error_SearchQueryInput_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded Keywords.
        /// </summary>
        public static string ConfigureCrawler_ExcludedKeywords {
            get {
                return ResourceManager.GetString("ConfigureCrawler_ExcludedKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All item entries containing any of specified excluded keywords will be filtered out..
        /// </summary>
        public static string ConfigureCrawler_ExcludedKeywords_HelpText {
            get {
                return ResourceManager.GetString("ConfigureCrawler_ExcludedKeywords_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword.
        /// </summary>
        public static string ConfigureCrawler_ExcludedKeywords_Hint {
            get {
                return ResourceManager.GetString("ConfigureCrawler_ExcludedKeywords_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        public static string ConfigureCrawler_Header {
            get {
                return ResourceManager.GetString("ConfigureCrawler_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ConfigureCrawler_Save {
            get {
                return ResourceManager.GetString("ConfigureCrawler_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least 2 characters.
        /// </summary>
        public static string ConfigureCrawler_SearchQuery_HelpText {
            get {
                return ResourceManager.GetString("ConfigureCrawler_SearchQuery_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search query.
        /// </summary>
        public static string ConfigureCrawler_SearchQuery_Placeholder {
            get {
                return ResourceManager.GetString("ConfigureCrawler_SearchQuery_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove text content from between 「 」.
        /// </summary>
        public static string ConfigureCrawler_TrimJapaneseQuotationMarks {
            get {
                return ResourceManager.GetString("ConfigureCrawler_TrimJapaneseQuotationMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to provide a title.
        /// </summary>
        public static string CrawlerSetDetails_Error_Title {
            get {
                return ResourceManager.GetString("CrawlerSetDetails_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string CrawlerSetDetails_Save {
            get {
                return ResourceManager.GetString("CrawlerSetDetails_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string CrawlerSetDetails_Title {
            get {
                return ResourceManager.GetString("CrawlerSetDetails_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawler set title.
        /// </summary>
        public static string CrawlerSetDetails_Title_HelpText {
            get {
                return ResourceManager.GetString("CrawlerSetDetails_Title_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add crawler.
        /// </summary>
        public static string CrawlerSetsPage_AddCrawlersHeader {
            get {
                return ResourceManager.GetString("CrawlerSetsPage_AddCrawlersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current crawlers.
        /// </summary>
        public static string CrawlerSetsPage_CurrentCrawlersHeader {
            get {
                return ResourceManager.GetString("CrawlerSetsPage_CurrentCrawlersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog.
        /// </summary>
        public static string Dialog_Changelog_Changelog {
            get {
                return ResourceManager.GetString("Dialog_Changelog_Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new excluded keywords.
        /// </summary>
        public static string EmptyState_Subtitle_ConfigureCrawler {
            get {
                return ResourceManager.GetString("EmptyState_Subtitle_ConfigureCrawler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added crawlers will show here..
        /// </summary>
        public static string EmptyState_Subtitle_CrawlerSetDetails {
            get {
                return ResourceManager.GetString("EmptyState_Subtitle_CrawlerSetDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawler sets will show up here..
        /// </summary>
        public static string EmptyState_Subtitle_CrawlerSets {
            get {
                return ResourceManager.GetString("EmptyState_Subtitle_CrawlerSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to show here....
        /// </summary>
        public static string EmptyState_Subtitle_Default {
            get {
                return ResourceManager.GetString("EmptyState_Subtitle_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create feed update job..
        /// </summary>
        public static string Error_FailedToCreateFeedUpdateJob {
            get {
                return ResourceManager.GetString("Error_FailedToCreateFeedUpdateJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Generic_Delete {
            get {
                return ResourceManager.GetString("Generic_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix any errors before saving.
        /// </summary>
        public static string Generic_FixError {
            get {
                return ResourceManager.GetString("Generic_FixError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawler Sets.
        /// </summary>
        public static string Hamburger_Item_CrawlerSets {
            get {
                return ResourceManager.GetString("Hamburger_Item_CrawlerSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed.
        /// </summary>
        public static string Hamburger_Item_Feed {
            get {
                return ResourceManager.GetString("Hamburger_Item_Feed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored Items.
        /// </summary>
        public static string Hamburger_Item_IgnoredItems {
            get {
                return ResourceManager.GetString("Hamburger_Item_IgnoredItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings &amp; More.
        /// </summary>
        public static string Hamburger_Item_Settings {
            get {
                return ResourceManager.GetString("Hamburger_Item_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watched Items.
        /// </summary>
        public static string Hamburger_Item_WatchedItems {
            get {
                return ResourceManager.GetString("Hamburger_Item_WatchedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price increase:.
        /// </summary>
        public static string Item_CrawlerCell_PriceIncrease {
            get {
                return ResourceManager.GetString("Item_CrawlerCell_PriceIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search phrase:.
        /// </summary>
        public static string Item_CrawlerCell_SearchPhrase {
            get {
                return ResourceManager.GetString("Item_CrawlerCell_SearchPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Phrase:.
        /// </summary>
        public static string Item_CrawlerDescriptor_SearchPhrase {
            get {
                return ResourceManager.GetString("Item_CrawlerDescriptor_SearchPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawlers:.
        /// </summary>
        public static string Item_CrawlerSet_Crawlers {
            get {
                return ResourceManager.GetString("Item_CrawlerSet_Crawlers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string Item_CrawlerSet_Empty {
            get {
                return ResourceManager.GetString("Item_CrawlerSet_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite.
        /// </summary>
        public static string Item_CrawlerSet_Favourite {
            get {
                return ResourceManager.GetString("Item_CrawlerSet_Favourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfavourite.
        /// </summary>
        public static string Item_CrawlerSet_Unfavourite {
            get {
                return ResourceManager.GetString("Item_CrawlerSet_Unfavourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to ignored.
        /// </summary>
        public static string Item_Feed_AddIgnore {
            get {
                return ResourceManager.GetString("Item_Feed_AddIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to watched.
        /// </summary>
        public static string Item_Feed_AddWatched {
            get {
                return ResourceManager.GetString("Item_Feed_AddWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed {0} ago.
        /// </summary>
        public static string Item_Feed_LastChanged {
            get {
                return ResourceManager.GetString("Item_Feed_LastChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from watched.
        /// </summary>
        public static string Item_Feed_RemoveWatched {
            get {
                return ResourceManager.GetString("Item_Feed_RemoveWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently updated.
        /// </summary>
        public static string Item_FeedChangeGroup_Recently {
            get {
                return ResourceManager.GetString("Item_FeedChangeGroup_Recently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored at: {0}.
        /// </summary>
        public static string Item_IgnoredItem_IgnoredAt {
            get {
                return ResourceManager.GetString("Item_IgnoredItem_IgnoredAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes content from 「 」.
        /// </summary>
        public static string Item_SurugayaCrawlerCell_TrimsFromQuotationMarks {
            get {
                return ResourceManager.GetString("Item_SurugayaCrawlerCell_TrimsFromQuotationMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FInished.
        /// </summary>
        public static string Item_WatchedItem_AuctionEnded {
            get {
                return ResourceManager.GetString("Item_WatchedItem_AuctionEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sold out.
        /// </summary>
        public static string Item_WatchedItem_SoldOut {
            get {
                return ResourceManager.GetString("Item_WatchedItem_SoldOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AoTracker.Android\Resources\values\app_resources.xml.
        /// </summary>
        public static string Meta_TargetAndroidFile {
            get {
                return ResourceManager.GetString("Meta_TargetAndroidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed update.
        /// </summary>
        public static string Notification_FeedUpdate {
            get {
                return ResourceManager.GetString("Notification_FeedUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are new changes on your feed!.
        /// </summary>
        public static string Notification_FeedUpdate_Description {
            get {
                return ResourceManager.GetString("Notification_FeedUpdate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure {0} Crawler.
        /// </summary>
        public static string PageTitle_ConfigureCrawlers {
            get {
                return ResourceManager.GetString("PageTitle_ConfigureCrawlers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed.
        /// </summary>
        public static string PageTitle_Feed {
            get {
                return ResourceManager.GetString("PageTitle_Feed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored Items.
        /// </summary>
        public static string PageTitle_IgnoredItems {
            get {
                return ResourceManager.GetString("PageTitle_IgnoredItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set &quot;{0}&quot; Details.
        /// </summary>
        public static string PageTitle_SetDetails {
            get {
                return ResourceManager.GetString("PageTitle_SetDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Set.
        /// </summary>
        public static string PageTitle_SetDetails_AddNew {
            get {
                return ResourceManager.GetString("PageTitle_SetDetails_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets.
        /// </summary>
        public static string PageTitle_Sets {
            get {
                return ResourceManager.GetString("PageTitle_Sets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings: About.
        /// </summary>
        public static string PageTitle_SettingsAbout {
            get {
                return ResourceManager.GetString("PageTitle_SettingsAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings: General.
        /// </summary>
        public static string PageTitle_SettingsGeneral {
            get {
                return ResourceManager.GetString("PageTitle_SettingsGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Index.
        /// </summary>
        public static string PageTitle_SettingsIndex {
            get {
                return ResourceManager.GetString("PageTitle_SettingsIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watched Items.
        /// </summary>
        public static string PageTitle_WatchedItems {
            get {
                return ResourceManager.GetString("PageTitle_WatchedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string PageTitle_Welcome {
            get {
                return ResourceManager.GetString("PageTitle_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply!.
        /// </summary>
        public static string Settings_General_Apply {
            get {
                return ResourceManager.GetString("Settings_General_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically load feed tab on scroll..
        /// </summary>
        public static string Settings_General_AutoLoadFeedTab {
            get {
                return ResourceManager.GetString("Settings_General_AutoLoadFeedTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you swipe on feed page the tab will load as soon as it becomes active, when disabled, manual load button will appear..
        /// </summary>
        public static string Settings_General_AutoLoadFeedTab_HelpText {
            get {
                return ResourceManager.GetString("Settings_General_AutoLoadFeedTab_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black theme.
        /// </summary>
        public static string Settings_General_BlackTheme {
            get {
                return ResourceManager.GetString("Settings_General_BlackTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Theme.
        /// </summary>
        public static string Settings_General_ColourThemeHeader {
            get {
                return ResourceManager.GetString("Settings_General_ColourThemeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark theme.
        /// </summary>
        public static string Settings_General_DarkTheme {
            get {
                return ResourceManager.GetString("Settings_General_DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default proxy:.
        /// </summary>
        public static string Settings_General_DefaultProxy {
            get {
                return ResourceManager.GetString("Settings_General_DefaultProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default proxy that will be used when handling item clicks or configuring price increase for crawlers..
        /// </summary>
        public static string Settings_General_DefaultProxy_HelpText {
            get {
                return ResourceManager.GetString("Settings_General_DefaultProxy_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule background feed update notification.
        /// </summary>
        public static string Settings_General_FeedUpdateJob {
            get {
                return ResourceManager.GetString("Settings_General_FeedUpdateJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App will periodically check for feed updates in backround and issue a notification when such change occurs..
        /// </summary>
        public static string Settings_General_FeedUpdateJob_HelpText {
            get {
                return ResourceManager.GetString("Settings_General_FeedUpdateJob_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate feed entry aggregating multiple sets..
        /// </summary>
        public static string Settings_General_GenerateFeedAggregate {
            get {
                return ResourceManager.GetString("Settings_General_GenerateFeedAggregate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First feed position will be one aggregating all favourited crawler sets..
        /// </summary>
        public static string Settings_General_GenerateFeedAggregate_HelpText {
            get {
                return ResourceManager.GetString("Settings_General_GenerateFeedAggregate_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light theme.
        /// </summary>
        public static string Settings_General_LightTheme {
            get {
                return ResourceManager.GetString("Settings_General_LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use price increase presets for selected default proxy.
        /// </summary>
        public static string Settings_General_PriceIncreasePresets {
            get {
                return ResourceManager.GetString("Settings_General_PriceIncreasePresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each proxy charges fees, they will be automatically filled in when configuring new crawler based on most common proxy rates..
        /// </summary>
        public static string Settings_General_PriceIncreasePresets_HelpText {
            get {
                return ResourceManager.GetString("Settings_General_PriceIncreasePresets_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AoTracker app information.
        /// </summary>
        public static string SettingsIndex_Entry_About_Subtitle {
            get {
                return ResourceManager.GetString("SettingsIndex_Entry_About_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string SettingsIndex_Entry_About_Title {
            get {
                return ResourceManager.GetString("SettingsIndex_Entry_About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application theme, and other settings.
        /// </summary>
        public static string SettingsIndex_Entry_General_Subtitle {
            get {
                return ResourceManager.GetString("SettingsIndex_Entry_General_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string SettingsIndex_Entry_General_Title {
            get {
                return ResourceManager.GetString("SettingsIndex_Entry_General_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only add up to five excluded keywords..
        /// </summary>
        public static string Toast_MaxCountOfExcludedKeywordsReached {
            get {
                return ResourceManager.GetString("Toast_MaxCountOfExcludedKeywordsReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Welcome_Finish {
            get {
                return ResourceManager.GetString("Welcome_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string Welcome_Skip {
            get {
                return ResourceManager.GetString("Welcome_Skip", resourceCulture);
            }
        }
    }
}
