//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AoTracker.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AoTracker.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase price .
        /// </summary>
        public static string ConfigureCrawler_Cost_OffsetIncrease {
            get {
                return ResourceManager.GetString("ConfigureCrawler_Cost_OffsetIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value will be added to the price after % increase.
        /// </summary>
        public static string ConfigureCrawler_Cost_OffsetIncrease_HelpText {
            get {
                return ResourceManager.GetString("ConfigureCrawler_Cost_OffsetIncrease_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase price by percentage.
        /// </summary>
        public static string ConfigureCrawler_Cost_PercentageIncrease {
            get {
                return ResourceManager.GetString("ConfigureCrawler_Cost_PercentageIncrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases the bases prices by given %.
        /// </summary>
        public static string ConfigureCrawler_Cost_PercentageIncrease_HelpText {
            get {
                return ResourceManager.GetString("ConfigureCrawler_Cost_PercentageIncrease_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least 3 characters.
        /// </summary>
        public static string ConfigureCrawler_SearchQuery_HelpText {
            get {
                return ResourceManager.GetString("ConfigureCrawler_SearchQuery_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search query....
        /// </summary>
        public static string ConfigureCrawler_SearchQuery_Placeholder {
            get {
                return ResourceManager.GetString("ConfigureCrawler_SearchQuery_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove text content from between 「 」.
        /// </summary>
        public static string ConfigureCrawler_TrimJapaneseQuotationMarks {
            get {
                return ResourceManager.GetString("ConfigureCrawler_TrimJapaneseQuotationMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure {0} Crawler.
        /// </summary>
        public static string PageTitle_ConfigureCrawlers {
            get {
                return ResourceManager.GetString("PageTitle_ConfigureCrawlers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed.
        /// </summary>
        public static string PageTitle_Feed {
            get {
                return ResourceManager.GetString("PageTitle_Feed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set &quot;{0}&quot; Details.
        /// </summary>
        public static string PageTitle_SetDetails {
            get {
                return ResourceManager.GetString("PageTitle_SetDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Set.
        /// </summary>
        public static string PageTitle_SetDetails_AddNew {
            get {
                return ResourceManager.GetString("PageTitle_SetDetails_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets.
        /// </summary>
        public static string PageTitle_Sets {
            get {
                return ResourceManager.GetString("PageTitle_Sets", resourceCulture);
            }
        }
    }
}
